services:
  obj-point-identifier:
    build: .
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=production
    
  obj-point-identifier-dev:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0
    profiles:
      - dev